config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]

  resources :careers
  resources :areas

  root 'careers#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :careers
  validates :name_area, length: { in: 1..30 , message: "Must be between 3 characters and 30"}

end

app/models/career.rb
class Career < ApplicationRecord
  belongs_to :area
  belongs_to :user

  validates :name_career, length: {in: 3...100, message: "Must be between 3 characters and 100"}
  validates :job_title, length: {in: 3...10000, message: "Must be between 3 characters and 10000"}
  validates :grade_title, length: {in: 3...100, message: "Must be between 3 characters and 100"}
  validates :duration,  presence: true
  validates :graduate_profile, length: {in: 3...10000, message: "Must be between 3 characters and 10000"}
  validates :occupational_field, length: {in: 3...10000, message: "Must be between 3 characters and 10000"}
  validates :area_id,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :adminis
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :careers

  validates :identity_document, presence: true
  validates_uniqueness_of :identity_document
  validates :email, format: { with: /@example\.cl\z/i }
  validates :username, length: {in: 3...1000, message: "Must be between 3 characters and 100"}
  validates :name, length: {in: 3...1000, message: "Must be between 3 characters and 100"}
  validates :lastname, length: {in: 3...1000, message: "Must be between 3 characters and 100"}

  def full_name
     "#{name} #{lastname}"
  end

  def email_com
     "#{email}"
  end

  private
  def adminis
    if email == "admin@example.cl"
      self[:admin] = true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username, :name, :lastname, :identity_document, :admin])
    devise_parameter_sanitizer.permit(:account_update, keys:[:username, :name, :lastname, :identity_document, :admin])
  end

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :find_area, only: [:show, :edit, :update, :destroy]

  def index
    @areas = Area.all
  end

  def new
    @area = Area.new
  end

  def show
  end

  def create
    @area= Area.new(area_params)

    if @area.save
      redirect_to areas_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @area.update(area_params)
      redirect_to areas_path(@area)
    else
      render 'edit'
    end
  end

  def destroy
    @area.destroy
    redirect_to areas_path
  end

  private
  def area_params
    params.require(:area).permit(:name_area)
  end

  def find_area
    @area = Area.find(params[:id])
  end

end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  before_action :find_career, only: [:show, :edit, :update, :destroy]

  def index
    if params[:area].blank?
      @careers = Career.all.order("created_at DESC")
    else
      @area_id = Area.find_by(name_area: params[:area]).id
      @careers = Career.where(:area_id => @area_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    #@career = Career.new
    @career = current_user.careers.build
    @areas = Area.all.map{|c| [c.name_area, c.id]}
  end

  def create
    @areas = Area.all.map{|c| [c.name_area, c.id]}
    #@career= Career.new(career_params)
    @career = current_user.careers.build(career_params)
    @career.area_id = params[:area_id]

    if @career.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @areas = Area.all.map{|c| [c.name_area, c.id]}
  end

  def update

    @career.area_id = params[:area_id]
    if @career.update(career_params)
      redirect_to career_path(@career)
    else
      render 'edit'
    end
  end

  def destroy
    @career.destroy
    redirect_to root_path
  end


  private
  def career_params
    params.require(:career).permit(:name_career, :job_title, :grade_title, :duration, :graduate_profile, :occupational_field)
  end
  def find_career
    @career = Career.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end

  end

  private
  def user_params
    params.require(:user).permit(:admin, :name, :lastname, :username, :identity_document)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/areas/_form.html.erb
<%= simple_form_for @area, :html => {:multipart =>true } do |f| %>

  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "Error") %> Before saving </h2>

      <ul>
        <% @area.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>

  <%= f.input :name_area, label: "University faculty" %>
  <%= f.button :submit,"Created Area"%>

  <%= link_to "Back",  areas_path%>

<%end%>

app/views/areas/edit.html.erb
<div class=" col-md-6 col-md-offset-3">
  <h1>Modicated Faculty</h1>

  <%= simple_form_for @area, :html => {:multipart =>true } do |f| %>

    <%= f.input :name_area %>
    <%= f.button :submit,"Modificated Faculty" %>

    <%= f.button :button do %>
      <%= link_to "Back", root_path %>
    <% end %>

  <%end%>
</div>

app/views/areas/index.html.erb
<div class=" col-md-6 col-md-offset-3">

    <h1>University Faculty</h1>
    <table>
      <body>
      <% @areas.each do |area| %>
        <tr>
          <h4><%=" - " %><%= link_to area.name_area, area_path(area)  %></h4>
        </tr>
      <%end %>
      </body>
    </table>

    <br>
    <%= link_to "Add faculty", new_area_path  %>
    <br>

    <%= link_to "Back", root_path %>
</div>

app/views/areas/new.html.erb
<div class=" col-md-6 col-md-offset-3">
    <h1>New Faculty</h1>

    <%= render 'form' %>
</div>

app/views/areas/show.html.erb
<div class=" col-md-6 col-md-offset-3">

    <h2> University Faculty </h2>
    <h3><%= @area.name_area %></h3>
    <br>
    <%= link_to "Back", areas_path  %>
    <%= link_to "edit Faculty", edit_area_path(@area) %>

</div>

app/views/careers/_form.html.erb
<%= simple_form_for @career, :html => {:multipart =>true } do |f| %>
  <% if @career.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@career.errors.count, "Errores") %> Antes de guardar: </h2>
      <ul>
        <% @career.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>

  <%= f.input :name_career, label: "Nombre Cargo" %>
  <%= select_tag(:area_id, options_for_select(@areas), :prompt => "Choose University Faculty ")%>
  <%= f.input :job_title %>
  <%= f.input :grade_title%>
  <%= f.input :duration%>
  <%= f.input :graduate_profile%>
  <%= f.input :occupational_field%>

  <%= f.button :submit %>

  <%= link_to "volver", root_path %>
<%end%>

app/views/careers/edit.html.erb
<h1>modificar cargo</h1>

<%= simple_form_for @career do |f| %>

  <% if @career.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@career.errors.count, "Errores") %> Antes de guardar: </h2>

      <ul>
        <% @career.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>


  <%= f.input :name_career, label: "Nombre Cargo" %>
  <%= select_tag(:area_id, options_for_select(@areas), :prompt => "Selecciona Area del Cargo")%>
  <%= f.input :job_title %>
  <%= f.input :grade_title%>
  <%= f.input :duration%>
  <%= f.input :graduate_profile%>
  <%= f.input :occupational_field%>

  <%= f.button :submit %>

  <%= link_to "volver", root_path %>

<%end%>

app/views/careers/index.html.erb
<div class=" col-md-10 col-md-offset-1">

<% if user_signed_in?%>

<h1><%= params[:area] %></h1>

  <%if @careers.count ==0 %>
    <h3> There is no publication </h3>
  <%else %>
    <h2>Careers Engineering</h2>

    <% @careers.each do |career| %>
      <h2><%= link_to career.name_career, career_path(career) %></h2>
      <h3><%= career.job_title %></h3>
      <h3><%= career.grade_title %></h3>
      <h3><%= career.graduate_profile %></h3>
    <% end %>
  <% end %>
<%else%>

  <h3>¿De qué se trata la Ingeniería?</h3>
  <p>
  Se trata de emplear todos los conocimientos científicos y tecnológicos para conversión de materiales y fuerzas de la naturaleza con el fin de inventar, desarrollar y mejorar las técnicas y herramientas para la resolución de problemas de todo tipo.
  Saber de qué se trata la Ingeniería es clave para evaluar la amplia variedad de carreras disponibles en esta área del conocimiento.
  </p>
  <h3>¿Qué necesito saber para estudiar Ingeniería?</h3>
  <p>
  El interés y vocación por las ciencias exactas es la base. Esto, además de gran capacidad de análisis y síntesis de datos, liderazgo, sin olvidar las habilidades para innovar y trabajar en equipo. Tener claro esto es clave para saber qué estudiar, especialmente si se trata de alguna Ingeniería.
  </p>
  <h3>¿Qué tipos de Ingeniería hay para estudiar?</h3>
  <p>
  Ya sabes, a grandes rasgos, de qué se trata esta área del conocimiento, pero ¿qué tipos de Ingeniería hay para estudiar? Entre las principales, vale la pena destacar las siguientes:
  </p>
  <h3>Ingeniería Civil en Mecánica</h3>
  <p>
  Forma profesionales en el ámbito de mantenimiento industrial, diseño y selección de equipos, instalaciones industriales y proceso de fabricación de manufactura.
  </p>
  <h3>Ingeniería Civil en Computación</h3>
  Se desarrolla en sistemas de información, telecomunicaciones, ciencias administrativas y económicas. Igualmente, servirá para desarrollar procesos en el área comercial, industrial, académico y de servicios.
  </p>
  <h3>Ingeniería en Geomensura</h3>
  <p>
  El egresado es capaz de resolver problemas de topografía, fotogrametría, geodesia y análisis espacio-territorial. Puede ejercer en consultoras de ingeniería o arquitectura, constructoras, mineras, forestales, agrícolas o geológicas.
  </p>
  <h3>Ingeniería Civil Electrónica</h3>
  <p>
  Forma profesionales con alto nivel tecnológico para gestionar, dirigir, diseñar y mantener sistemas electrónicos en empresas modernas.
  </p>
  <h3>Ingeniería Civil en Ciencia de Datos</h3>
  <p>
  El objetivo general es generar, transferir, aplicar y difundir el conocimiento científico y tecnológico. Se puede desempeñar como director de proyectos, consultor de sistemas en ambientes big data, planificador estratégico en sistema de computación y gestión de datos.
  </p>
  <h3>Ingeniería Industrial</h3>
  <p>
    El estudiante es capaz de desarrollarse en empresas que utilicen tecnología de punta. Se desenvuelve como especialista en productividad, proceso y planificación de actividades organizacionales en instituciones públicas o privadas.
  Programa de bachillerato en Ciencias de la Ingeniería
  Se trata de un programa que busca abrir oportunidades para quienes quieren seguir alguna Ingeniería, pero aún no se deciden del todo. El programa de bachillerato tiene una duración de 2 años e integra las bases necesarias para el futuro estudiante de Ingeniería.
  </p>

<% end %>
</div>

app/views/careers/new.html.erb
<div class=" col-md-6 col-md-offset-3">
  <h1>New Engineering</h1>

  <%= render 'form' %>

</div>

app/views/careers/show.html.erb
<div class=" col-md-10 col-md-offset-1">
    <h2><%= @career.name_career %></h2>
    <h2>Facultad: <%= @career.area.name_area %></h2>
    <h3>Job Title: <%= @career.job_title %></h3>
    <h3>Grade Title: <%= @career.grade_title %></h3>
    <h3>Duration: <%= @career.duration %> Semestre</h3>
    <h3>Graduate Profile:</h3>
  <%= @career.graduate_profile%>
    <h3>Occupatonal Field:</h3>
  <%= @career.occupational_field %>

    <%= link_to "Back", root_path %>
    <%= link_to "edit", edit_career_path(@career) %>
    <%= link_to "Delete", career_path(@career), method: :delete, data:{ confirm: "¿Estas seguro?"}%>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">

  <div class="container">

    <div class="navbar-header">
      <%= link_to "Career", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav navbar-right">

      <% if user_signed_in?%>
        <li class=" dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Areas <span class="caret"></span></a>
          <ul class ="dropdown-menu" role="menu">
            <% Area.all.each do |area| %>
              <li class="<%='active' if params[:area] ==area.name_area %>" >
                <%= link_to area.name_area, careers_path(area: area.name_area), class: "link"  %>
              </li>
            <% end %>

            <% if user_signed_in?%>
              <% if current_user && current_user.admin %>
                <li><%= link_to "Add Area", areas_path%></li>
              <%end%>
            <%end%>
          </ul>
        </li>
        <% if current_user.admin?%>
          <li><%= link_to "users", users_path %></li>
          <li><%= link_to "Add Career", new_career_path %></li>
        <%end%>
        <li><%= link_to current_user.email, user_path(current_user) %> </li>

        <li><%= link_to "salir", destroy_user_session_path, method: :delete %></li>
      <%else%>
        <li><%=link_to "Registrarse", new_user_registration_path %></li>
        <li><%=link_to "Entrar", new_user_session_path %></li>
      <%end%>


    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EngineeringDecision</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => {:multipart =>true } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "Error") %> Antes de guardar: </h2>

      <ul>
        <% @career.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>

      </ul>
    </div>
  <%end%>

  <h1>Editar Usuario</h1>

  <h1><%= @user.email_com %></h1>

  <%= f.input :username, label: "Userame"%>
  <%= f.input :name, label: "Name"%>
  <%= f.input :lastname, label: "Last name"%>
  <%= f.input :identity_document, label: "identity_document"%>

  <% if current_user.admin?%>
    <%= f.input :admin, label: "Administrador"%>

    <h2> <%= f.button :submit,"Modificar datos"%></h2>


    <%= f.button :button do %>
      <%= link_to "cancelar", users_path %>
    <% end %>

    <%= f.button :button do %>
      <%= link_to "volver", users_path %>
    <% end %>
  <%else%>

    <%= f.button :submit,"Modificar datos"%>
    <%= f.button :button do %>
      <%= link_to "cancelar", user_path %>
    <% end %>
  <%end%>

<% end %>

app/views/users/_user.html.erb
<h4>Email: <%= link_to user.email_com, user  %></h4>
<h5>Name: <%= user.name %></h5>
<h5>Last Name: <%= user.lastname %></h5>
<h5>Username:  <%= user.username %></h5>
<h5>identity_document: <%= user.identity_document %></h5>
<h5>Administrador:  <%= user.admin %></h5>

app/views/users/edit.html.erb
<div class=" col-md-6 col-md-offset-3">
    <h1>Users edit</h1>
    <%= render 'form', user: @user %>
    <p>Find me in app/views/users/edit.html.erb</p>
</div>

app/views/users/index.html.erb
<div class=" col-md-6 col-md-offset-3">
    <h1>Users#index</h1>
    <ul>
      <%= render @users %>
    </ul>

</div>

app/views/users/show.html.erb
<div class=" col-md-6 col-md-offset-3">
    <h1>User Detail</h1>

    <h3>Email: <%= @user.email_com %></h3>
    <h5>Name: <%= @user.name %></h5>
    <h5>Last Name: <%= @user.lastname %></h5>
    <h5>Username:  <%= @user.username %></h5>
    <h5>identity_document: <%= @user.identity_document %></h5>

    <% if current_user.admin?%>
      <%= link_to "editar",edit_user_path(@user), class: 'btn-custom2' %>
      <%= link_to "volver", users_path, class: 'btn-custom2' %>
    <%else%>
      <%= link_to "editar",edit_user_path(current_user), class: 'btn-custom2' %>
      <%= link_to "volver", root_path, class: 'btn-custom2' %>
    <%end%>
</div>